name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    name: Build & Release (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release package
        shell: powershell
        run: |
          .\build.ps1

      - name: Archive Release
        shell: powershell
        run: |
          Compress-Archive -Path release\* -DestinationPath simple-jingle-windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: simple-jingle-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
